import * as YAML from "js-yaml";

import { State } from "../state";
import { PathResolver } from "../../path";
import { Buffer } from "buffer";
import { Derivation } from "./abstract";

/**
 * Builds the configuration for Yarn.
 */
export class YarnDerivation implements Derivation {
  public getFilePath(): string {
    return ".yarnrc.yml";
  }

  public makeDerivation(state: State, project: PathResolver): Buffer {
    let contents: string = `#
# STOP! This file is automatically generated.
#
# To add your own configuration options to .yarnrc.yml,
# add them to rocket.yml, then run "rocket sync".
#
`;
    contents += YAML.dump({
      yarnPath: ".yarn/releases/yarn-berry.cjs",
      nodeLinker: state.yarn.linker,
    });
    return Buffer.from(contents, "utf-8");
  }
}
