import { Buffer } from "buffer";
import { Derivation } from "./abstract";
import { Config } from "../config";
import { PathResolver } from "../../path";
import { PersistenceFile } from "../file";
import { Credentials } from "../credentials";

/**
 * Builds the .gitignore.
 */
export class GitIgnoreDerivation implements Derivation {
  filePath = ".gitignore";
  toolId = "git";

  private readonly derivations: readonly Derivation[];

  public constructor(derivations: readonly Derivation[]) {
    this.derivations = derivations;
  }

  public async makeDerivation(
    config: PersistenceFile<Config>
  ): Promise<Buffer> {
    let contents: string = `#
# STOP! This file is automatically generated.
#
# To add your own rules to this .gitignore,
# add them to rocket.yml, then run "rocket sync".
#

# File explorer metadata
.DS_Store
thumbs.db

# IDE settings
.idea/
.vscode/

# Node
node_modules

# Yarn
yarn-error.log
.yarn/*
!.yarn/releases
!.yarn/plugins
!.yarn/sdks
!.yarn/versions
.pnp.*

# TypeScript
build/
tsconfig.tsbuildinfo

# Rocket-managed files
.rocket/
`;

    // add derivation files to gitignore - rocket manages these
    contents += this.derivations
      .map((derivation) => `${derivation.filePath}\n`)
      .join("");

    // add custom rules
    contents += ["\n# Custom rules\n"]
      .concat(config.gitignore.map((rule) => `${rule}\n`))
      .join("");

    return Buffer.from(contents, "utf-8");
  }
}
